BINARY_NAME=celeritasApp.exe

build:
	@go build -o tmp/${BINARY_NAME} .
	@echo Celeritas built!

run: build 
	@echo Staring Celeritas...
	@start /B tmp\${BINARY_NAME} &
	@echo Celeritas started!

clean:
	@echo Cleaning...
	@DEL ${BINARY_NAME}
	@go clean
	@echo Cleaned!

test:
	@echo Testing...
	@go test ./...
	@echo Done!

start: run
	
stop:
	@echo "Starting the front end..."
	@taskkill /IM ${BINARY_NAME} /F
	@echo Stopped Celeritas

restart: stop start